### ISSUE TITLE
tests for baseball cards ask for faceUp and isFaceUp properties

### ISSUE THREAD

**Issue by vicfriedman** [learn-co-curriculum/OOP-Cards-Model#13]
the baseball card tests ask for faceUp and isFaceUp properties that are not listed in the readme

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by markedwardmurray** [comment]
those properties have been removed in the rewrite
https://github.com/learn-co-curriculum/OOP-Cards-Model/pull/15
